### ISSUE TITLE
Sudden fatal error

### ISSUE THREAD

**Issue by daveloodts** [dpdconnect/woocommerce-shipping#44]
Hi, without any reason we got this fatal error; as a result we could not login in to wordpress; and the woocommerce checkout was not functioning.

Fri Aug 12 13:18:17.875868 2022] [error] [pid 4000207] mod_proxy_fcgi.c(887): [client xxx] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /xxx/plugins/dpdconnect/classes/Connect/Product.php:21\nStack trace:\n#0 /xxxx/plugins/dpdconnect/classes/Connect/Product.php(69): DpdConnect\\classes\\Connect\\Product->getList()\n#1 /xxxx/plugins/dpdconnect/classes/Connect/Product.php(42): DpdConnect\\classes\\Connect\\Product->getProductsByType()\n#2 /xxxx/plugins/dpdconnect/classes/Connect/Product.php(58): DpdConnect\\classes\\Connect\\Product->getAllowedProducts()\n#3 /xxxx/plugins/dpdconnect/classes/shippingmethods/DPDShippingMethod.php(102): DpdConnect\\classes\\Connect\\Product->getProductByCode()\n#4 /xxxx/plugins/dpdconnect/classes/shippingmethods/DPDShippingMethod.php(96): DpdConnect\\classes\\shippingmethods\\DPDShippingMethod->init_dpd()\n#5 /xxxx/www/wp-con...'

we have the version 1.3.7.
I took out the plugin via FTP; then able to login, activate DPD plugin, and it's all good.
What could be the case here?

**Comment by dpdplugin** [comment]
Hi @daveloodts ,
We would like to investigate this further but we need some more information that's confidential.
Could you send us an email at support@x-interactive.nl with your DPD username?

**Comment by rvdsteege** [comment]
I stumbled upon the same issue today and did some research. In our case — and I'm guessing the same was true for @daveloodts — it appears that a request to https://api.dpdconnect.nl/api/connect/v1/available-products sometimes results in an `error code: 1015` response:

```shell
curl -H "Accept: application/json" -H "Authorization: Bearer ⏺⏺⏺⏺⏺⏺" "https://api.dpdconnect.nl/api/connect/v1/available-products?limit=20&with_count=0"
error code: 1015
```

As **api.dpdconnect.nl** uses Cloudflare, this error code is probably due to rate limiting:
- https://support.cloudflare.com/hc/en-us/articles/360029779472-Troubleshooting-Cloudflare-1XXX-errors#error1015

Probably unintended, but I found the erroneous response being cached to disk and then returned in:
- https://github.com/dpdconnect/php-sdk/blob/12cabc0e204c56e5e9a7ff1fdde4492810cce6a2/src/Resources/Product.php#L23-L26

Based on these findings, I think the exception for the HTTP 500 response is not thrown:
- https://github.com/dpdconnect/php-sdk/blob/12cabc0e204c56e5e9a7ff1fdde4492810cce6a2/src/Common/HttpClient.php#L253-L260

Hopefully this can be fixed in a future plugin update. I've manually added a `string` check to resolve the issue for now:

```php
        if ($result && ! is_string( $result ) ) {
            return $result;
        }
```

**Comment by rvdsteege** [comment]
@dpdplugin I just noticed this fatal error was 'kind of' resolved in the latest plugin release (https://github.com/dpdconnect/woocommerce-shipping/releases/tag/1.4.4). However, that still leaves the underlying rate limiting error being cached to disk, if I'm not mistaken (I didn't check).

I will update the plugin on our client website, which should at least prevent any further fatal errors without any manual code changes.

**Comment by dpdplugin** [comment]
Hi @rvdsteege
Thanks for finding this out and we will definitly take this with us in a future update, we limit the available products endpoint at 5 requests per 10 seconds (per IP).
